services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./db:/data
      - ./redis.conf:/etc/redis/redis.conf
  # api:
  #   image: node:18-alpine
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./src:/app/src
  #     - ./src:/app/src
  #     - ./static:/app/static
  server:
    image: macbre/nginx-brotli:1.19.6-http3
    user: "root"
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/html
